version = 0.1
[default.deploy.parameters]
stack_name = "ws-serverless-patterns-userprofile"
resolve_s3 = true
s3_prefix = "ws-serverless-patterns-userprofile"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UserPool=\"eu-west-1_Nr16G8BL2\" Service=\"userprofile\" Stage=\"prod\""
image_repositories = []
